### ISSUE TITLE
RSS request

### ISSUE THREAD

**Issue by yuandi42** [alpha-beta-eta/alpha-beta-eta.github.io#1]
I recently stumbled upon this site and was really impressed by your articles. However, I noticed that your website currently lacks an RSS feed (or I am too stupid to find it). Hence, I kindly request your consideration in adding a feed, as it would greatly enhance the convenience of following your updates.

**Comment by alpha-beta-eta** [comment]
I've added an RSS feed to my homepage. Thank you for your suggestion.
